# Generated by Django 5.0.4 on 2024-05-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelrequestapp", "0002_rename_username_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(default="NULL", max_length=254),
        ),
    ]
