# Generated by Django 5.0.4 on 2024-05-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelrequestapp", "0003_userprofile_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("supervisor", models.BooleanField(default=False)),
            ],
        ),
    ]
