# Generated by Django 5.0.4 on 2024-05-06 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelrequestapp", "0004_supervisor"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelAuthForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("today_date", models.DateField()),
                ("submitted_by", models.CharField(max_length=100)),
                ("signature", models.CharField(max_length=100)),
                ("date_of_travel_from_date", models.DateField()),
                ("date_of_travel_to_date", models.DateField()),
                ("conference_name", models.CharField(max_length=200)),
                ("conference_location", models.CharField(max_length=100)),
                ("reason_for_travel", models.TextField()),
                (
                    "people_travelling",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("hotel_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "conference_registration_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "airfare_train_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "car_rental_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "other_misc_costs",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_estimated_costs",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("comments", models.TextField()),
                ("supervisor", models.CharField(max_length=100)),
                ("associate_director", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "travel_auth_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travelrequestapp.travelauthform",
                    ),
                ),
            ],
        ),
    ]
