# Generated by Django 5.0.4 on 2024-05-20 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelrequestapp", "0005_travelauthform_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelauthform",
            name="first_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="travelauthform",
            name="second_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="travelauthform",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="travelrequestapp.userprofile",
            ),
        ),
    ]
