# Generated by Django 4.2.11 on 2024-05-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelrequestapp", "0006_travelauthform_first_approval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelauthform",
            name="submitted_by",
            field=models.CharField(max_length=100),
        ),
    ]
