# Generated by Django 5.0.4 on 2024-06-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelrequestapp", "0007_alter_travelauthform_submitted_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travelauthform",
            name="submitted_by",
        ),
        migrations.AddField(
            model_name="travelauthform",
            name="final_approval_status",
            field=models.CharField(
                choices=[
                    ("Approval", "Approval"),
                    ("Pending", "Pending"),
                    ("Rejected", "Rejected"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="travelauthform",
            name="submitted_by_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="travelrequestapp.userprofile",
            ),
        ),
    ]
