# Generated by Django 5.0.4 on 2024-06-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travelrequestapp", "0008_remove_travelauthform_submitted_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="travelauthform",
            old_name="submitted_by_id",
            new_name="submitted_by",
        ),
    ]
