# Generated by Django 5.0.4 on 2024-06-27 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelrequestapp", "0009_rename_submitted_by_id_travelauthform_submitted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelauthform",
            name="submitted_by",
            field=models.ForeignKey(
                db_column="submitted_by",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="travelrequestapp.userprofile",
            ),
        ),
    ]
